using CarPurchasePlatform.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPurchasePlatform.Repositories
{
    public class InMemoryYearRepository : IYearRepository
    {
        public Task<Response<IEnumerable<Year>>> GetAsync()
        {
            return Task.FromResult(new Response<IEnumerable<Year>>(new List<Year>()
                   {
                        new Year(2021, "Audi", "A6"),
                        new Year(2020, "Audi", "A6"),
                        new Year(2019, "Audi", "A6"),
                        new Year(2018, "Audi", "A6"),
                        new Year(2017, "Audi", "A6"),
                        new Year(2016, "Audi", "A6"),
                        new Year(2015, "Audi", "A6"),
                        new Year(2014, "Audi", "A6"),
                        new Year(2013, "Audi", "A6"),
                        new Year(2012, "Audi", "A6"),
                        new Year(2011, "Audi", "A6"),
                        new Year(2005, "Audi", "A1"),
                        new Year(2006, "Audi", "A1"),
                        new Year(2007, "Audi", "A1"),
                        new Year(2008, "Audi", "A1"),
                        new Year(2009, "Audi", "A1"),
                        new Year(2010, "Audi", "A1"),
                        new Year(2011, "Audi", "A1"),
                        new Year(2012, "Audi", "A1"),
                        new Year(2013, "Audi", "A1"),
                        new Year(2002, "Audi", "A2"),
                        new Year(2003, "Audi", "A2"),
                        new Year(2004, "Audi", "A2"),
                        new Year(2005, "Audi", "A2"),
                        new Year(2006, "Audi", "A2"),
                        new Year(2007, "Audi", "A2"),
                        new Year(2007, "Audi", "A2"),
                        new Year(2015, "Audi", "A7"),
                        new Year(2016, "Audi", "A7"),
                        new Year(2017, "Audi", "A7"),
                        new Year(2018, "Audi", "A7"),
                        new Year(2019, "Audi", "A7"),
                        new Year(2020, "Audi", "A7"),
                        new Year(2021, "Audi", "A8"),
                        new Year(2020, "Audi", "A8"),
                        new Year(2019, "Audi", "A8"),
                        new Year(2017, "Audi", "Q5"),
                        new Year(2018, "Audi", "Q5"),
                        new Year(2019, "Audi", "Q5"),
                        new Year(2020, "Audi", "Q5"),
                        new Year(2019, "Audi", "Q7"),
                        new Year(2020, "Audi", "Q7"),
                        new Year(2021, "Audi", "Q7"),
                        new Year(1978, "BMW", "M1"),
                        new Year(1979, "BMW", "M1"),
                        new Year(1980, "BMW", "M1"),
                        new Year(1981, "BMW", "M1"),
                        new Year(2016, "BMW", "M2"),
                        new Year(2017, "BMW", "M2"),
                        new Year(2018, "BMW", "M2"),
                        new Year(2019, "BMW", "M2"),
                        new Year(2020, "BMW", "M2"),
                        new Year(2014, "BMW", "M4"),
                        new Year(2015, "BMW", "M4"),
                        new Year(2016, "BMW", "M4"),
                        new Year(2017, "BMW", "M4"),
                        new Year(2018, "BMW", "M4"),
                        new Year(2019, "BMW", "M4"),
                        new Year(2020, "BMW", "M4"),
                        new Year(2021, "BMW", "M4"),
                        new Year(2009, "BMW", "X1"),
                        new Year(2010, "BMW", "X1"),
                        new Year(2011, "BMW", "X1"),
                        new Year(2012, "BMW", "X1"),
                        new Year(2013, "BMW", "X1"),
                        new Year(2014, "BMW", "X1"),
                        new Year(2015, "BMW", "X1"),
                        new Year(2016, "BMW", "X1"),
                        new Year(2017, "BMW", "X1"),
                        new Year(2018, "BMW", "X1"),
                        new Year(2019, "BMW", "X1"),
                        new Year(2020, "BMW", "X1"),
                        new Year(2021, "BMW", "X1"),
                        new Year(1999, "BMW", "X5"),
                        new Year(2000, "BMW", "X5"),
                        new Year(2001, "BMW", "X5"),
                        new Year(2002, "BMW", "X5"),
                        new Year(2003, "BMW", "X5"),
                        new Year(2004, "BMW", "X5"),
                        new Year(2005, "BMW", "X5"),
                        new Year(2006, "BMW", "X5"),
                        new Year(2007, "BMW", "X5"),
                        new Year(2008, "BMW", "X5"),
                        new Year(2009, "BMW", "X5"),
                        new Year(2010, "BMW", "X5"),
                        new Year(2011, "BMW", "X5"),
                        new Year(2012, "BMW", "X5"),
                        new Year(2013, "BMW", "X5"),
                        new Year(2014, "BMW", "X5"),
                        new Year(2015, "BMW", "X5"),
                        new Year(2016, "BMW", "X5"),
                        new Year(2017, "BMW", "X5"),
                        new Year(2018, "BMW", "X5"),
                        new Year(1999, "Honda", "S2000"),
                        new Year(2000, "Honda", "S2000"),
                        new Year(2001, "Honda", "S2000"),
                        new Year(2002, "Honda", "S2000"),
                        new Year(2003, "Honda", "S2000"),
                        new Year(2004, "Honda", "S2000"),
                        new Year(2005, "Honda", "S2000"),
                        new Year(2006, "Honda", "S2000"),
                        new Year(2007, "Honda", "S2000"),
                        new Year(2008, "Honda", "S2000"),
                        new Year(2009, "Honda", "S2000"),
                        new Year(2019, "Honda", "Accord"),
                        new Year(2020, "Honda", "Accord"),
                        new Year(2021, "Honda", "Accord"),
                        new Year(1990, "Honda", "NSX"),
                        new Year(1991, "Honda", "NSX"),
                        new Year(1992, "Honda", "NSX"),
                        new Year(1993, "Honda", "NSX"),
                        new Year(1994, "Honda", "NSX"),
                        new Year(1995, "Honda", "NSX"),
                        new Year(1996, "Honda", "NSX"),
                        new Year(1997, "Honda", "NSX"),
                        new Year(1998, "Honda", "NSX"),
                        new Year(1999, "Honda", "NSX"),
                        new Year(2000, "Honda", "NSX"),
                        new Year(2001, "Honda", "NSX"),
                        new Year(2002, "Honda", "NSX"),
                        new Year(2003, "Honda", "NSX"),
                        new Year(2004, "Honda", "NSX"),
                        new Year(2005, "Honda", "NSX"),
                        new Year(2015, "Honda", "Jazz"),
                        new Year(2016, "Honda", "Jazz"),
                        new Year(2017, "Honda", "Jazz"),
                        new Year(2018, "Honda", "Jazz"),
                        new Year(2019, "Honda", "Jazz"),
                        new Year(2020, "Honda", "Jazz"),
                        new Year(2021, "Honda", "Jazz"),
                        new Year(2017, "Honda", "Civic"),
                        new Year(2018, "Honda", "Civic"),
                        new Year(2019, "Honda", "Civic"),
                        new Year(2020, "Honda", "Civic"),
                        new Year(2021, "Honda", "Civic"),
                        new Year(2011, "Volkswagen", "Golf"),
                        new Year(2012, "Volkswagen", "Golf"),
                        new Year(2013, "Volkswagen", "Golf"),
                        new Year(2014, "Volkswagen", "Golf"),
                        new Year(2015, "Volkswagen", "Golf"),
                        new Year(2016, "Volkswagen", "Golf"),
                        new Year(2017, "Volkswagen", "Golf"),
                        new Year(2018, "Volkswagen", "Golf"),
                        new Year(2019, "Volkswagen", "Golf"),
                        new Year(2020, "Volkswagen", "Golf"),
                        new Year(2021, "Volkswagen", "Golf"),
                        new Year(2021, "Volkswagen", "Passat"),
                        new Year(2020, "Volkswagen", "Golf"),
                        new Year(2019, "Volkswagen", "Golf"),
                        new Year(2018, "Volkswagen", "Golf"),
                        new Year(2017, "Volkswagen", "Golf"),
                        new Year(2016, "Volkswagen", "Golf"),
                        new Year(2015, "Volkswagen", "Golf"),
                        new Year(2014, "Volkswagen", "Golf"),
                        new Year(2013, "Volkswagen", "Golf"),
                        new Year(2012, "Volkswagen", "Golf"),
                        new Year(2011, "Volkswagen", "Golf"),
                        new Year(2010, "Volkswagen", "Golf"),
                        new Year(2017, "Volkswagen", "Pantheon"),
                        new Year(2018, "Volkswagen", "Pantheon"),
                        new Year(2019, "Volkswagen", "Pantheon"),
                        new Year(2020, "Volkswagen", "Pantheon"),
                        new Year(2015, "Volkswagen", "Caddy"),
                        new Year(2016, "Volkswagen", "Caddy"),
                        new Year(2017, "Volkswagen", "Caddy"),
                        new Year(2015, "Volkswagen", "Polo"),
                        new Year(2016, "Volkswagen", "Caddy"),
                        new Year(2017, "Volkswagen", "Caddy"),
                        new Year(2018, "Volkswagen", "Caddy")
                   }));
        }

        public Task<Response<IEnumerable<Year>>> GetAsync(string manufacturer, string model)
        {
            return GetAsync().ContinueWith((result) =>
            {
                var response = result.Result;
                if (response.ResponseType == ErrorTypeEnum.Success)
                    return new Response<IEnumerable<Year>>(response.Content.Where(x => x.Manufacturer == manufacturer && x.Model == model).ToList());
                else
                    return new Response<IEnumerable<Year>>(response.ErrorMessage, response.ResponseType);
            });
        }
    }
}
